### ISSUE TITLE
CCI Partner Orb Review

### ISSUE THREAD

**Issue by KyleTryon** [sysdiglabs/circleci-orb#5]
Hello,

My name is Kyle from the CircleCI CPE team. I have reviewed your orb and have a few suggestion items below.

- Never use "strings" for secret values. Instead _expect_ the name of an environment variable.
  - https://github.com/sysdiglabs/circleci-orb/blob/912798cb55eafb7cc72e427c8bac41451b79d17d/src/commands/inline-image-scan.yml#L7
  - https://circleci.com/docs/2.0/orbs-best-practices/#secrets-should-never-be-directly-entered
- Update usage examples to reflect above change
- change `advanced_example` name to reflect what use-case this example showcases.

-- 

Looking at the orb I wonder too if this orb should have job(s), potentially even in-place of commands instead. In the use-cases shown it appears as though it would be common to supply a docker container (or image) and scan.

These self-contained actions seem like a perfect use-case for a job that a user could simply add to their existing workflows.
https://circleci.com/docs/2.0/orb-author-faq/#command-vs-job

**Comment by KyleTryon** [comment]
CC @tembleking ^

**Comment by manuelbcd** [comment]
Hi @KyleTryon , according to this doc I'm realizing that we can left the environment variables as they are with notation ${VAR} 

Is that right or would we consider a good practice to switch them to $VAR notation?

Thank you

**Comment by KyleTryon** [comment]
> ding to this doc I'm realizing that we can left the environment variables as they are with notation ${VAR}
> Is that right or would we consider a good practice to switch them to $VAR notation?

`${}` vs `$` will just be a consideration of how you are utilizing an environment variable in Bash. If you are inserting an environment variable in a string in bash, you will need to use `{}`. For the purposes of the orb, this is not relevant. From the orb perspective, we just want to ensure that the parameter references the name of an environment variable which your script will look for.

Example:
https://github.com/CircleCI-Public/github-cli-orb/blob/b12cb675b6512ce0c4a434a28714f7eecbb7db8c/src/commands/setup.yml#L7

https://github.com/CircleCI-Public/github-cli-orb/blob/main/src/scripts/setup.sh#L6

**Comment by manuelbcd** [comment]
Pls @KyleTryon have a look into https://github.com/sysdiglabs/circleci-orb/commit/7af2873566cd2f8bfb8b28824f91bef705fa8562 

Thanks!

**Comment by manuelbcd** [comment]
@KyleTryon, the error seems a bit weird to me since in theory "SYSDIG_API_TOKEN=${SECURE_API_TOKEN}" has no brackets and no dollar sign in the repository... do you know if we need to do any manual step in the circleci pipeline to avoid this error?
![image](https://user-images.githubusercontent.com/10448961/148088797-433f95aa-3651-4052-b2d7-a30f7f903bb0.png)

**Comment by KyleTryon** [comment]
@manuelbcd

The issue here is not related to your code. You can not access the docker.sock because we do not give access to privileged containers on the Docker executor for security reasons. If you require this, you will be limited to using the machine executor (a VM) and running Docker within it, or alternatively, you can use the `setup_remote_docker` command within docker.

https://support.circleci.com/hc/en-us/articles/115015849028-Docker-Daemon-Not-Available

**Comment by manuelbcd** [comment]
@KyleTryon, the problem was in our inline scanner image latest version, after rolling it back to 2.4.5 it works again (the team will fix the bug asap).

We proceed to close the issue. 

Thank you
